USE TestDB
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF OBJECT_ID('GRLS.attribute_level_1', 'U') IS NOT NULL
DROP TABLE GRLS.attribute_level_1
GO

CREATE TABLE GRLS.attribute_level_1
(
	l1_id		int IDENTITY(1, 1)	NOT NULL ,
	l1_desc		varchar(50)			NOT NULL ,
	abbrev		char(4)				NOT NULL
)
GO
ALTER TABLE GRLS.attribute_level_1 ADD PRIMARY KEY CLUSTERED 
(
	l1_id ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
