USE TestDB
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF OBJECT_ID('Grls.region', 'U') IS NOT NULL
DROP TABLE Grls.region
GO

CREATE TABLE Grls.region
(
	id				int IDENTITY(1, 1)	NOT NULL ,
	region_name		varchar(50)			NOT NULL
)
GO
ALTER TABLE Grls.region ADD PRIMARY KEY CLUSTERED 
(
	id ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
