USE TestDB
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF OBJECT_ID('Grls.eye_colour', 'U') IS NOT NULL
DROP TABLE Grls.eye_colour
GO

CREATE TABLE Grls.eye_colour
(
	id				int IDENTITY(1, 1)	NOT NULL ,
	colour_desc		varchar(50)			NOT NULL ,
	pref_level		int					NOT NULL
)
GO
ALTER TABLE Grls.eye_colour ADD PRIMARY KEY CLUSTERED 
(
	id ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
