USE [master]
ALTER DATABASE [TestDB] SET SINGLE_USER WITH ROLLBACK IMMEDIATE
RESTORE DATABASE [TestDB] FROM  DISK = N'/var/opt/mssql/data/TestDB-20250711-20-12-00.bak' WITH  FILE = 1,  NOUNLOAD,  REPLACE,  STATS = 5
ALTER DATABASE [TestDB] SET MULTI_USER
